[package]
name = "orbuffer-gui"
version = "0.1.0"
description = "OrBuffer desktop GUI"
license = "Apache-2.0"
edition = "2021"

[lib]
name = "orbuffer_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = "2"

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "rustls-tls", "json"] }
serde_json = "1"
tauri = "2"
url = "2"
